In [1]:
import numpy as np

In [2]:
#1D Array
a= np.array([1,2,3])
print (a)
print (type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D Array
b=np.array([[1,2,3],[2,4,6]])
print(b)

[[1 2 3]
 [2 4 6]]


In [4]:
#Checking number of dimensions
b.ndim

2

In [5]:
# Converting a 2D array to 5D
c=np.array([[1,2],[3,4]],ndmin=5)
c           

array([[[[[1, 2],
          [3, 4]]]]])

In [6]:
c.ndim

5