In [1]:
import numpy as np

# 1D Array

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Slicing from first to 5th element
a[:5]

array([1, 2, 3, 4, 5])

In [4]:
#Slicing from 6th to last element
a[5:]

array([ 6,  7,  8,  9, 10])

In [5]:
#Slicing from 2nd to 8th element
a[1:8]

array([2, 3, 4, 5, 6, 7, 8])

In [6]:
#Negative Slicing
a[-10:-5]

array([1, 2, 3, 4, 5])

In [7]:
# Slicing by stepping two numbers
# a[0:10:2]
a[::2]

array([1, 3, 5, 7, 9])

# 2D Array

<h3>Row</h3>

In [8]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#Slicing from second to last element in row
b[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [10]:
#Slicing third element only
# b[2:3]
b[2,...]

array([7, 8, 9])

In [11]:
#Printing first two elements of 2nd dimension
b[1,:2]

array([4, 5])

<h3>Column</h3>

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#Printing the first column
b[...,0]

array([1, 4, 7])

In [14]:
#Slicing from second to last element in column
b[...,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])