In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
# Copy is a new array
c=a.copy()
c

array([1, 2, 3, 4])

In [4]:
# View is just a view of original array
v=a.view()
v

array([1, 2, 3, 4])

In [5]:
# Changes to copy doesn't affect to original array
c[0]=10
print(a)
print(c)

[1 2 3 4]
[10  2  3  4]


In [6]:
# Changes to view affects to original array
v[0]=10
print(a)
print(v)

[10  2  3  4]
[10  2  3  4]


In [7]:
# Check whether the array is copy or view
print(c.base)
print(v.base)

None
[10  2  3  4]
